### ISSUE TITLE
Trouble with multiple morphs in a sentence.

### ISSUE THREAD

**Issue by NinKenDo64** [NinKenDo64/Jieba-Morph#1]
For some reason only expressions which contain a single morph will get their focus morph field filled. This happens regardless of whether the morph appears more than once in the expression, just so long as there are no others.

**Comment by kaegi** [comment]
Can you give an example/elaborate a bit more? I'm not sure I can follow what's happening...

The focus morph field will only be set for expressions which contain a single unknown morpheme. If the expression has multiple unknowns or the only unknown morpheme becomes unmature*, the field will be cleared. This behavior is intentional.

*edit: mature

**Comment by NinKenDo64** [comment]
I fixed this issue a while back.
